mucsci-students/2023sp-420-G-J-IFY

README.md

- Filled out template for README.md
- Added name and contact info at bottom under Authors
- Created basic file structure and started adding essential files.

README.md edit, began basic file structure

---

.gitignore
MANIFEST.in
setup.cfg
setup.py

Created the basic project structure and necessary files.

Finalized basic project structure

---

src/spelling_bee/StateStorage.py

created a stateStorage module that we can import to handle saving. I only added a few functions along with some helper functions. I would like either Jacob or Yah to approve this since they are a part of the saving team.

State storage module

---

src/SpellingBee/generateSubset.py

Generate Subset of words for game

---

src/SpellingBee/generateSubset.py

funciton to getAllWordsFromPangram

Updated wording in generateSubset, changed key

---

src/SpellingBee/generateMaxScore.py

Updated max score and DB to reflect pangram scoring

added findMaxScore function, updated DB

---

src/SpellingBee/showPuzzle.py

push showPuzzle

---

src/SpellingBee/StateStorage.py
src/SpellingBee/saveState.py

made __load and __ save take different params and made functions to take the saveState obj and turn it into a dictionary and made another function that takes a dictionary and sets the fields of obj to the values in the dictionary and added setters to saveState. before you approve this ensure that __main__.py didn't get messed up because then I pulled the repo __main__.py was empty (I tried multiple times)

added and fixed saveState and StateStorage

---

.gitignore
src/SpellingBee/MakePuzzle.py
src/SpellingBee/generateSubset.py
src/SpellingBee/saveState.py

actual tweaks to guess and whatnot

JakeUnfucksHisFuckups2

---

src/SpellingBee/MakePuzzle.py

Fixed upper case letter problem, caught 2 bugs that I'll have to address later

fixed upper case letter input for user choice key letter

---

src/SpellingBee/MakePuzzle.py
src/SpellingBee/generateMaxScore.py
src/SpellingBee/generateSubset.py
src/SpellingBee/saveState.py

Added second copy of wordDict.db to top level for VSCode to
stop bitching at me

Modified relative DB paths to just 'wordDict.db'

---

flapjack.json
src/SpellingBee/saveState.py

Setup save file that is one guess off from queenbee, only missing 'FLAPJACK'

Fixed rank bug in saveState, now works up to QueenBee

---

src/SpellingBee/CommandHandler.py

Fixed !puzzle not displaying correctly bug

Fixed !puzzle being different from the normal puzzle

---

.gitignore

Update .gitignore with defualt python .gitignore

---

src/SpellingBee/MakePuzzle.py

Fixed several issues in MakePuzzle, notabley how non-alpha or mixed case guesses/starting words are made

GuessExcept

---

src/SpellingBee/StateStorageTests.py
src/SpellingBee/allTests.py
src/SpellingBee/saveStateTests.py

Tieing all tests together

---

src/SpellingBee/MakePuzzleTests.py

MakePuzzle Tests

---

src/model/MakePuzzle.py
src/model/saveState.py

Updated maxScore to only reference the DB with precalulated max scores.
Removed a lot of helper functions that are now meaningless.

Refactor MaxScore

---

StyleGuide.md
src/controller/CommandHandler.py
src/cview/CLI.py
src/gview/ButtonCluster.py
src/gview/MainWindow.py
src/gview/WordsWidget.py

created comment styleguide
properly documented CLI and CommandHandler

Documentation

---

.gitignore
.vscode/settings.json
StyleGuide.md

added ruler settings

---

src/model/StateStorage.py
tests/saveCheckerTest.py

saveChecker implemented fully. 
Tweaked some other code to work with it correctly. 
Still need to refactor print statements in here, as well as DB path, but this fully funcitons for CLI

Save Game Checker implemented

---

src/gview/Dialogs.py
src/gview/MainWindow.py

Created New dialog box

---

src/gview/Dialogs.py
src/gview/LoadDialog.py
src/gview/MainWindow.py

Created Load dialog that prompts user for file name.
Create Load Failed dialog that notifies the user that the load failed.

Added Load dialogs

---

src/model/MakePuzzle.py
src/model/StateStorage.py
src/model/__init__.py
src/model/dbFixer.py

new moduel

---

README.md

easier readme without pip installs.

simple readme

---

Makefile
src/controller/CommandHandler.py
src/controller/GController.py
src/gview/Dialogs.py
src/gview/HexCluster.py
src/gview/MainWindow.py
src/gview/StatsPanel.py
src/model/MakePuzzle.py
src/model/puzzle.py

View_shit_again

---

src/controller/gController/GController.py
src/model/StateStorage.py

left my test code at the bottom of StateStorage win you want to test.

new load function and file explorer opener

---

src/model/MakePuzzle.py

caught edge case of user entering keyletters string > len1

Fix KeyLetter bug

---

src/controller/gController/GController.py
src/gview/HexCluster.py
src/gview/MainWindow.py

Center letter is now properly centered after creating a new game.
Solution: Changed GController.newPuzzle from using `puzzle.getUniqueLetters()` to `puzzle.getShuffleLetters()`

Fixed center letter issue when creating new game

---

src/controller/cController/__main__.py

Also removed double lines that got depricated with outty

End Game Flag Fix

---

src/controller/gController/GController.py
src/gview/Dialogs.py
src/gview/MainWindow.py

Fixed advanced tab in new dialog

New-game-advanced

---

src/controller/cController/CommandHandler.py
src/model/StateStorage.py

fixed overwriting on both mac and windows

Fixing overwriting save bug on windows

---

src/controller/cController/CommandHandler.py
src/controller/cController/__main__.py

Problemw as a recursive function call. Now just updating puzzle to None object and looping if that happens in start of game loop

Fix to new game loop

---

src/controller/gController/GController.py
src/gview/MainWindow.py

Fixed shuffle button and save game dialog window.

GControllerSave

---

src/gview/StatsPanel.py

Removed underline from level label

Removed underline

---

src/controller/gController/GController.py

needed to move to the saves folder then move back out.

fix Bug with overwriting a save

---

src/gview/StatsPanel.py

Added extra line to StatsPanel.ptsToNxt displaying the players current score.

Added Score to Stats Panel

---

src/controller/gController/GController.py
src/gview/MainWindow.py

fixed status bar not clearing on new/load game

Added status.clear() to MainWindow.newGame()

---

spellingbee/model/StateStorage.py

This introduces patches to the missing center letter error and the deleted good words error

Client Issues Fixed

---

spellingbee/tests/test_Puzzle.py

finished puzzle tests 100% code cov

Puzzle tests

---

README.md
spellingbee/controller/gController/GController.py

Slapped a solution to not crash the game for GUI, minor update to readMe

MoreBugHunt

---

.vscode/settings.json
StyleGuide.md
spellingbee/View/CLI/CLI.py
spellingbee/View/GUI/Dialogs.py
spellingbee/controller/cController/CommandHandler.py
spellingbee/controller/gController/GController.py
spellingbee/model/MakePuzzle.py
spellingbee/model/StateStorage.py
spellingbee/model/hint.py
spellingbee/model/output.py
spellingbee/model/puzzle.py

This pull request takes care of most, if not all, documentation as of now to adhere to our documentation guide.

Documentation fixes

---

.vscode/settings.json
spellingbee/tests/test_MakePuzzleTests.py
spellingbee/tests/test_Puzzle.py
spellingbee/tests/test_StateStorageTests.py
spellingbee/tests/test_hintTests.py

Cleaned up code base using Flake8. This PR has cleaned up all of the tests folder

Flake8 Linting - Tests

---

spellingbee/controller/GUIAdapter.py
spellingbee/controller/cController/CLIAdapter.py

Client's issue to fix in GUI and CLI.

Fixing two letter list formatting

---

spellingbee/model/MakePuzzle.py
spellingbee/model/hint.py
spellingbee/tests/test_MakePuzzleTests.py

Adding-tests

---

.gitignore

virtual environment should not be tracked.

added venv/ to gitignore

---

spellingbee/controller/cController/CLIAdapter.py
spellingbee/model/StateStorage.py
spellingbee/tests/test_StateStorageTests.py

Still an issue with loading a bad json from the CLI (lines 278, 291). 
Test written is failing, some issue with being in the wrong directory. If Gaige can take a look at this we should be able to get tests to 100%

Fix StateStorage, get tests to 98%

---

spellingbee/controller/GUIAdapter.py
spellingbee/controller/cmd.py

CLI works with new save stuffs

Cmd-encrypt

---

spellingbee/gview/style.css

Fixed unreadable text in dark mode

removed custom text color to textbox

---

spellingbee/controller/GUIAdapter.py
spellingbee/gview/Dialogs.py
spellingbee/gview/MainWindow.py
spellingbee/gview/WrapUp.py

Exit Game no longer provides save option, save added to options menu

No-highscore-on-save

---

spellingbee/controller/cController/CLIAdapter.py

Removing crash from the cli temporarily.

Fixing quick cli crash

---

spellingbee/cview/CLI.py

Added score and points till next rank to main gamebox in CLI

Added extra info to cli game box

---

spellingbee/controller/cController/CLIAdapter.py
spellingbee/controller/cController/__main__.py

Renamed commands and ensured auto-complete works
